# Generated by Django 3.1.1 on 2020-09-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200926_1851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
