# Generated by Django 3.1.1 on 2020-09-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200926_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
