# Generated by Django 3.1.1 on 2020-09-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200926_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_num',
            new_name='phone_number',
        ),
    ]
