# Generated by Django 3.1.1 on 2020-09-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.URLField(blank=True)),
                ('price', models.FloatField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
