# Generated by Django 3.1.1 on 2020-09-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
    ]
