# Generated by Django 3.1.1 on 2020-09-25 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200925_2319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
