# Generated by Django 3.1.1 on 2020-09-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200927_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetables', 'vegetables'), ('fruits', 'fruits'), ('something unusual', 'something unusual')], max_length=25),
        ),
    ]
